### ISSUE TITLE
Documentación Conceptos teóricos sobre las medusas

### ISSUE THREAD

**Issue by psnti** [psnti/Jellyfish_Forecast_TFG_Pablo_Santidrian_Tudanca#25]

**Comment by alvarag** [comment]
Buenas tardes,

Adjunto comentarios sobre la memoria y anexos:

[anexosAAG.pdf](https://github.com/psnti/TFG-Pablo-Santidrian-Tudanca/files/4370122/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/psnti/TFG-Pablo-Santidrian-Tudanca/files/4370125/memoriaAAG.pdf)


Saludos,
